title: Kai Fabi blog
author: 
    name: Kai Fabi
    email: str('kaifabi')+'@'+'.'.join(['posteo','net'])

description: >- # this means to ignore newlines until "baseurl:"
  Fun with neural networks and more. I basically brain dump here anything that comes to my mind.

show_excerpts: false

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaifabi.github.io" # the base hostname & protocol for your site
github_username: kaifabi
twitter_username: _kaifabi

minima:
    date_format: "%b %-d, %Y"
    social_links:
        twitter: _kaifabi
        github: kaifabi

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
